[project]
name = "function-calling"
version = "0.1.0"
description = "Experimenting with function calling in Gemma 3"
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.5.1",
    "rich>=14.0.0",
]
